module.exports = {
  "zh-tw": {
    htmlLang: "zh-TW",
    hreflang: "zh-Hant",
    path: "/zh-tw/",
    title: "畢弘偉 Ansel Bi — 策展人 / App 程式設計師",
    description:
      "策展人 Ansel Bi，近二十年策展經歷，策劃近六十場展覽，足跡遍及亞洲、歐洲、美洲、澳洲。將策展美學注入獨立開發的 APP 與貼圖。",
    keywords:
      "畢弘偉, Ansel Bi, 策展人, 獨立開發者, ProfitFairy, 小主私密日記, 艾奧斯, 台客柴, MeowCAT",
    chinese_name: "畢弘偉",
    name_en: "Ansel Bi",
    nav_works: "作品",
    nav_stickers: "貼圖",
    nav_curator: "策展",
    slogan: "將策展的沉默，編譯為數位的詩行",
    role: "策展人 / App 程式設計師",
    hero_desc:
      "台灣\n一個倉庫裡\n\n父親的作品\n在我面前\n\n不是欣賞\n是打包\n\n打棧板 釘木箱 貼標籤 纏膠帶\n\n然後\n那些木箱飛越半個地球\n\n直到它們抵達\n紐約 曼哈頓\n\n那年是2009\n\n展場裡 拆封 擦拭\n小心翼翼地安放在牆上\n\n等待燈光亮起\n\n那是我策劃的第一場展覽\n策展人是兒子\n藝術家是父親\n\n我從父親的作品裡學會了聆聽\n不是聆聽掌聲\n而是聆聽一件作品從木箱裡被取出時\n那道細微的 幾乎聽不見的呼吸聲\n\n還有燈亮之後\n有人走進來\n安靜地站在作品前\n那份沉默\n比任何話語都誠實\n\n近二十年過去了\n\n我策劃了近六十場展覽\n足跡走過亞洲 歐洲 美洲 澳洲\n做過私人美術館顧問\n為藝術家策劃過個展與聯展\n也為藏家與機構提供諮詢\n\n但我始終沒有忘記那個倉庫\n\n沒有忘記釘木箱敲打的聲音\n\n如今\n我將那份聆聽那份細膩的節奏\n帶進App與貼圖裡\n它們是我與使用者之間\n一次次無聲的共振\n\n就像當年那盞燈\n輕輕落在父親的作品上\n\n然後\n有人停下來\n\n安靜地\n看了很久\n\n或許\n那個人就是你",
    stat1_num: "20",
    stat1_txt: "年策展經歷",
    stat2_num: "≈60",
    stat2_txt: "場展覽策劃",
    stat3_num: "4",
    stat3_txt: "大洲足跡",
    apps_title: "原創應用",
    sticker_title: "iMessage 貼圖",
    pf_title: "ProfitFairy 毛利率利潤定價計算機",
    pf_sub: "商業・生產力工具",
    pf_desc:
      "專為電商與實體商家設計的利潤管理系統。一鍵拆分成本、運費、稅金、平台費，即時計算多項參數混搭並支援歷史紀錄查看，讓每個商業決策精準透明。",
    ruby_title: "小主私密日記－月經經期排卵日曆",
    ruby_sub: "生理期追蹤、月經排卵期計算器・女性私密日記",
    ruby_desc:
      "生理期與排卵期精準計算日曆，同時是一本可上鎖的私密日記。融合《黃帝內經》等四大中醫典籍，提供穴位與藥膳食補指南。記錄每一天的心情、照片與身體變化。",
    aios_title: "艾奧斯 (AIOS Realm)",
    aios_sub: "解謎・卡牌・故事",
    aios_desc:
      "顛覆傳統2048的立體化腦力解謎。透過十字合成、女神卡牌召喚與記憶碎片重組，逐步解鎖海洋女神的史詩劇情。燒腦策略與抽卡收集並行。",
    taiger_name: "【台客柴】阿柴的江湖日常：俗擱有力篇",
    taiger_sub: "藍白拖＋復古安全帽＋超派口頭禪，看起來很兇其實超北爛",
    meow1_name: "MeowCAT-1: 辦公室貓爪",
    meow1_sub: "你的每日可愛劑量 / Your Daily Dose of Cuteness",
    meow2_name: "MeowCAT-2: 職場崩潰日記",
    meow2_sub: "囂張不改，崩潰常來 / Sassy & Stressed-out",
    meow3_name: "MeowCAT-3: 隔間喵趣",
    meow3_sub: "用一聲喵，說一切 / Say It with a Meow",
    curator_title: "聆聽，然後共振",
    curator_sub: "策展筆記 · 從展場到螢幕",
    curator_p1:
      "策展是一條長河\n\n學會的不是如何展示\n而是如何聆聽\n聆聽作品自身的語言\n聆聽空間的呼吸\n聆聽觀者沉默的凝視\n\n真正的展覽\n是讓這三者找到共振的頻率",
    curator_p2:
      "後來\n這份聆聽被帶進數位世界\n\n每一個App 每一款貼圖\n都不再只是單方面的設計\n像從前聆聽作品那樣\n聆聽每一個使用者的聲音\n他們的想法 困惑 期盼\n一點一滴滲進程式碼裡\n\n這些作品\n是使用者與創作者共同完成的形狀\n\n從來不是那個單獨塑造氛圍的人\n試著站在不同的位置上\n去感受 去揣摩 去共振\n\n小主私密日記是一個例子\n\n一個男性\n要如何設計一個陪伴女性生理期的工具\n沒有答案\n只能去聽 去讀\n去想像那些永遠無法親身經歷的日常\n\n正是這種未知\n讓創作有了溫柔的可能\n\nApp也是這樣\n它們不是被封裝的成品\n而是等待被聆聽 被共鳴 被一起完成的\n\n如同當年曼哈頓\n那盞燈亮起之後\n\n有人安靜地站在父親的作品前\n\n看了很久\n\n策展如此\n創作亦如此\n\n永不落幕",
    expo_role1: "個展策劃 / Solo Exhibitions",
    expo_detail1: "足跡橫跨亞洲、歐洲、美洲、澳洲，為多位藝術家策劃個人展覽",
    expo_role2: "聯展統籌 / Group Shows",
    expo_detail2: "統籌主題性聯展，梳理群體創作中的對話脈絡",
    expo_role3: "藝術博覽會 / Art Fairs",
    expo_fair_note: "諸如 ",
    expo_fair1: "ArtExpo New York / 紐約藝術博覽會 ",
    expo_fair2: "Art Shopping – Carrousel du Louvre / 法國巴黎羅浮宮卡魯塞爾藝術博覽會 ",
    expo_fair3: "Art Taipei / 台北藝術博覽會 ",
    expo_fair4: "AArt Shanghai / 上海城市藝術博覽會 ",
    expo_fair_more: " 等",
    expo_role4: "藝術顧問 / Art Advisor",
    expo_detail4: "私人美術館顧問、藏家與藝術機構策展諮詢",
    expo_note: "足跡遍及四大洲 — 近六十場展覽策劃實踐",
    contact_btn: "聯絡 / 合作",
    contact_note: "策展合作 · 開發委託 · 品牌聯名 · 用戶反饋",
    privacy_link: "隱私權政策",
  },
  "zh-cn": {
    htmlLang: "zh-CN",
    hreflang: "zh-Hans",
    path: "/zh-cn/",
    title: "毕弘伟 Ansel Bi — 策展人 / App 程序员",
    description:
      "策展人 Ansel Bi，近二十年策展经历，策划近六十场展览，足迹遍及亚洲、欧洲、美洲、澳洲。将策展美学注入独立开发的 APP 与贴图。",
    keywords:
      "毕弘伟, Ansel Bi, 策展人, 独立开发者, ProfitFairy, 小主私密日记, 艾奥斯, 台客柴, MeowCAT",
    chinese_name: "毕弘伟",
    name_en: "Ansel Bi",
    nav_works: "作品",
    nav_stickers: "贴图",
    nav_curator: "策展",
    slogan: "将策展的沉默，编译为数字的诗行",
    role: "策展人 / App 程序员",
    hero_desc:
      "台湾\n一个仓库里\n\n父亲的作品\n在我面前\n\n不是欣赏\n是打包\n\n打栈板 钉木箱 贴标签 缠胶带\n\n然后\n那些木箱飞越半个地球\n\n直到它们抵达\n纽约 曼哈顿\n\n那年是2009\n\n展场里 拆封 擦拭\n小心翼翼地安放在墙上\n\n等待灯光亮起\n\n那是我策划的第一场展览\n策展人是儿子\n艺术家是父亲\n\n我从父亲的作品里学会了聆听\n不是聆听掌声\n而是聆听一件作品从木箱里被取出时\n那道细微的 几乎听不见的呼吸声\n\n还有灯亮之后\n有人走进来\n安静地站在作品前\n那份沉默\n比任何话语都诚实\n\n近二十年过去了\n\n我策划了近六十场展览\n足迹走过亚洲 欧洲 美洲 澳洲\n做过私人美术馆顾问\n为艺术家策划过个展与联展\n也为藏家与机构提供咨询\n\n但我始终没有忘记那个仓库\n\n没有忘记钉木箱敲打的声音\n\n如今\n我将那份聆听那份细腻的节奏\n带进App与贴图里\n它们是我与使用者之间\n一次次无声的共振\n\n就像当年那盏灯\n轻轻落在父亲的作品上\n\n然后\n有人停下来\n\n安静地\n看了很久\n\n或许\n那个人就是你",
    stat1_num: "20",
    stat1_txt: "年策展经历",
    stat2_num: "≈60",
    stat2_txt: "场展览策划",
    stat3_num: "4",
    stat3_txt: "大洲足迹",
    apps_title: "原创应用",
    sticker_title: "iMessage 贴图",
    pf_title: "ProfitFairy 毛利率利润定价计算器",
    pf_sub: "商业・生产力工具",
    pf_desc:
      "专为电商与实体商家设计的利润管理系统。一键拆分成本、运费、税金、平台费，即时计算多项参数混搭并支持历史纪录查看，让每个商业决策精准透明。",
    ruby_title: "小主私密日记－月经经期排卵日历",
    ruby_sub: "生理期追踪、月经排卵期计算器・女性私密日记",
    ruby_desc:
      "生理期与排卵期精准计算日历，同时是一本可上锁的私密日记。融合《黄帝内经》等四大中医典籍，提供穴位与药膳食补指南。记录每一天的心情、照片与身体变化。",
    aios_title: "艾奥斯 (AIOS Realm)",
    aios_sub: "解谜・卡牌・故事",
    aios_desc:
      "颠覆传统2048的立体化脑力解谜。透过十字合成、女神卡牌召唤与记忆碎片重组，逐步解锁海洋女神的史诗剧情。",
    taiger_name: "【台客柴】阿柴的江湖日常：俗搁有力篇",
    taiger_sub: "蓝白拖＋复古安全帽＋超派口头禅，看起来很凶其实超北烂",
    meow1_name: "MeowCAT-1: 办公室猫爪",
    meow1_sub: "你的每日可爱剂量 / Your Daily Dose of Cuteness",
    meow2_name: "MeowCAT-2: 职场崩溃日记",
    meow2_sub: "嚣张不改，崩溃常来 / Sassy & Stressed-out",
    meow3_name: "MeowCAT-3: 隔间喵趣",
    meow3_sub: "用一声喵，说一切 / Say It with a Meow",
    curator_title: "聆听，然后共振",
    curator_sub: "策展笔记 · 从展场到屏幕",
    curator_p1:
      "策展是一条长河\n\n学会的不是如何展示\n而是如何聆听\n聆听作品自身的语言\n聆听空间的呼吸\n聆听观者沉默的凝视\n\n真正的展览\n是让这三者找到共振的频率",
    curator_p2:
      "后来\n这份聆听被带进数字世界\n\n每一个App 每一款贴图\n都不再只是单方面的设计\n像从前聆听作品那样\n聆听每一个使用者的声音\n他们的想法 困惑 期盼\n一点一滴渗进代码里\n\n这些作品\n是使用者与创作者共同完成的形状\n\n从来不是那个单独塑造氛围的人\n试着站在不同的位置上\n去感受 去揣摩 去共振\n\n小主私密日记是一个例子\n\n一个男性\n要如何设计一个陪伴女性生理期的工具\n没有答案\n只能去听 去读\n去想象那些永远无法亲身经历的日常\n\n正是这种未知\n让创作有了温柔的可能\n\nApp也是这样\n它们不是被封装的成品\n而是等待被聆听 被共鸣 被一起完成的\n\n如同当年曼哈顿\n那盏灯亮起之后\n\n有人安静地站在父亲的作品前\n\n看了很久\n\n策展如此\n创作亦如此\n\n永不落幕",
    expo_role1: "个展策划 / Solo Exhibitions",
    expo_detail1: "足迹横跨亚洲、欧洲、美洲、澳洲，为多位艺术家策划个人展览",
    expo_role2: "联展统筹 / Group Shows",
    expo_detail2: "统筹主题性联展，梳理群体创作中的对话脉络",
    expo_role3: "艺术博览会 / Art Fairs",
    expo_fair_note: "诸如 ",
    expo_fair1: "ArtExpo New York / 纽约艺术博览会 ",
    expo_fair2: "Art Shopping – Carrousel du Louvre / 法国巴黎罗浮宫卡鲁塞尔艺术博览会 ",
    expo_fair3: "Art Taipei / 台北艺术博览会 ",
    expo_fair4: "AArt Shanghai / 上海城市艺术博览会 ",
    expo_fair_more: " 等",
    expo_role4: "艺术顾问 / Art Advisor",
    expo_detail4: "私人美术馆顾问、藏家与艺术机构策展咨询",
    expo_note: "足迹遍及四大洲 — 近六十场展览策划实践",
    contact_btn: "联络 / 合作",
    contact_note: "策展合作 · 开发委托 · 品牌联名 · 用户反馈",
    privacy_link: "隐私权政策",
  },
  en: {
    htmlLang: "en",
    hreflang: "en",
    path: "/en/",
    title: "Ansel Bi — Curator / App Developer",
    description:
      "Curator and indie app developer Ansel Bi. Nearly 20 years curating ~60 exhibitions across four continents. Bringing curatorial aesthetics to original apps and iMessage stickers.",
    keywords:
      "Ansel Bi, curator, indie developer, ProfitFairy, RubyDays, AIOS Realm, Taiger Shiba, MeowCAT",
    chinese_name: "",
    name_en: "Ansel Bi",
    nav_works: "Works",
    nav_stickers: "Stickers",
    nav_curator: "Curating",
    slogan: "Compiling curatorial silence into digital poetry",
    role: "Curator / App Developer",
    hero_desc:
      "Taiwan\nInside a warehouse\n\nMy father's work\nBefore me\n\nNot to admire it\nTo pack it\n\nPalletizing nailing crates taping labels wrapping tape\n\nThen\nThose crates flew halfway across the world\n\nUntil they arrived\nIn New York Manhattan\n\nThat year was 2009\n\nInside the gallery unpacking wiping\nPlacing each piece gently on the wall\n\nWaiting for the lights to come up\n\nThat was my first exhibition as a curator\nThe curator was a son\nThe artist was his father\n\nFrom my father's work I learned to listen\nNot to applause\nBut to the faint almost inaudible breath\nOf a piece being lifted from its crate\n\nAnd after the lights came up\nSomeone would walk in\nAnd stand quietly in front of the work\nThat silence\nWas more honest than any words\n\nNearly twenty years have passed\n\nI have curated nearly sixty exhibitions\nTraveling across Asia Europe the Americas and Australia\nServed as a private museum advisor\nCurated solo and group shows for artists\nAnd offered consultation to collectors and institutions\n\nBut I have never forgotten that warehouse\n\nNever forgotten the sound of hammering nails into crates\n\nNow\nI bring that same listening that same delicate rhythm\nInto apps and stickers\nThey are the silent resonance\nBetween me and every user\n\nLike that light\nSoftly falling on my father's work\n\nThen\nSomeone stopped\n\nQuietly\nLooked for a long long time\n\nPerhaps\nThat someone is you",
    stat1_num: "20",
    stat1_txt: "Years",
    stat2_num: "≈60",
    stat2_txt: "Exhibitions",
    stat3_num: "4",
    stat3_txt: "Continents",
    apps_title: "Original Apps",
    sticker_title: "iMessage Stickers",
    pf_title: "ProfitFairy: Gross Margin Calc",
    pf_sub: "Business · Productivity",
    pf_desc:
      "Profit management for e-commerce & retail. Split costs, shipping, taxes, platform fees instantly, calculate multiple mixed parameters in real time with history log support. Precision for every decision.",
    ruby_title: "RubyDays: TCM Herbal Wellness Calendar",
    ruby_sub: "Period Tracker, Ovulation Calculator & Private Diary",
    ruby_desc:
      "Accurate period & ovulation calendar, plus a lockable private diary. Integrates 4 TCM classics, acupressure, and medicinal recipes. Record daily moods, photos, and physical changes.",
    aios_title: "AIOS Realm: Divinity Reborn",
    aios_sub: "Puzzle · Cards · Story",
    aios_desc:
      "A 2048-evolution puzzle game. Merge goddess cards, unlock epic oceanic narrative. Strategic brain-teaser meets card collection.",
    taiger_name: "Taiger Shiba: Jianghu Daily",
    taiger_sub: "Blue slippers + retro helmet + gangster phrases. Looks fierce but hilariously silly",
    meow1_name: "MeowCAT-1: Office Paws",
    meow1_sub: "Your Daily Dose of Cuteness",
    meow2_name: "MeowCAT-2: Corporate Meltdown",
    meow2_sub: "Sassy & Stressed-out",
    meow3_name: "MeowCAT-3: Cubicle Tails",
    meow3_sub: "Say It with a Meow",
    curator_title: "Listen, Then Resonate",
    curator_sub: "Curatorial Notes · From Galleries to Screens",
    curator_p1:
      "Curating is a long river\n\nWhat I learned was not how to display\nBut how to listen\nTo listen to the language of the work\nThe breath of the space\nThe silent gaze of the viewer\n\nA true exhibition\nIs where these three find a frequency of resonance",
    curator_p2:
      "Later\nThat listening found its way into the digital world\n\nEvery app every sticker\nIs no longer just a one-sided design\nJust as I once listened to artworks\nI now listen to every user's voice\nTheir thoughts their confusions their hopes\nSeeping into the code drop by drop\n\nThese works\nAre shapes co-created by users and the creator\n\nI am never the one who shapes the atmosphere alone\nI try to stand in different positions\nTo feel to empathize to resonate\n\nRubyDays is one example\n\nHow does a man design a tool\nTo accompany women through their cycles\nI don't have the answer\nI can only listen read\nAnd imagine the daily realities I will never experience firsthand\n\nIt is precisely this unknown\nThat gives creation its gentle possibility\n\nApps are the same\nThey are not sealed finished products\nThey are things waiting to be heard to be resonated with to be completed together\n\nJust like that night in Manhattan\nAfter the lights came up\n\nSomeone stood quietly in front of my father's work\n\nAnd looked for a long time\n\nCurating is like this\nCreation is like this\n\nIt never ends",
    expo_role1: "Solo Exhibitions",
    expo_detail1: "Spanning Asia Europe Americas Australia curated solo shows for multiple artists",
    expo_role2: "Group Shows",
    expo_detail2: "Organized thematic group exhibitions articulating dialogues within collective creations",
    expo_role3: "Art Fairs",
    expo_fair_note: "Including ",
    expo_fair1: "ArtExpo New York ",
    expo_fair2: "Art Shopping – Carrousel du Louvre ",
    expo_fair3: "Art Taipei ",
    expo_fair4: "AArt Shanghai ",
    expo_fair_more: " among others",
    expo_role4: "Art Advisor",
    expo_detail4: "Consulting for private museums collectors and art institutions",
    expo_note: "Spanning four continents nearly sixty curated exhibitions",
    contact_btn: "Contact / Collaborate",
    contact_note: "Curatorial · Development · Brand Collaboration · Feedback",
    privacy_link: "Privacy Policy",
  },
};
