module.exports = {
  "zh-tw": {
    htmlLang: "zh-TW",
    hreflang: "zh-Hant",
    path: "/zh-tw/",
    title: "畢弘偉 Ansel Bi — 策展人 / App 程式設計師",
    description:
      "策展人 Ansel Bi，近二十年策展經歷，策劃近六十場展覽，足跡遍及亞洲、歐洲、美洲、澳洲。將策展美學注入獨立開發的 APP 與貼圖。",
    keywords:
      "畢弘偉, Ansel Bi, 策展人, 獨立開發者, ProfitFairy, 小主私密日記, 艾奧斯, 台客柴, MeowCAT",
    chinese_name: "畢弘偉",
    name_en: "Ansel Bi",
    nav_works: "作品",
    nav_stickers: "貼圖",
    nav_curator: "策展",
    slogan: "將策展的沉默，編譯為數位的詩行",
    role: "策展人 / App 程式設計師",
    hero_desc:
      "某個倉庫裡\n\n滿倉的畫\n靜止在我面前\n\n不是欣賞\n是打包\n\n打棧板 釘木箱 貼標籤 纏膠帶\n\n然後\n這些大傢伙\n落在比台北慢十二個鐘的曼哈頓\n\n那年是雷曼風暴過後\n等待燈光亮起的2009\n\n策展人是兒子\n藝術家是父親\n\n那是我印象最深的一場策展\n\n我從父親的作品裡學會了聆聽\n不是聆聽掌聲\n而是聆聽一件作品從木箱裡被取出時\n那道細微的 幾乎聽不見的呼吸聲\n\n還有燈亮之後\n有人走進來\n安靜地站在作品前\n那份沉默\n比任何話語都誠實\n\n近二十年過去了\n\n我策劃了近六十場展覽\n足跡走過亞洲 歐洲 美洲 澳洲\n做過私人美術館顧問\n為藝術家策劃過個展與聯展\n也為藏家與機構提供諮詢\n\n但我始終沒有忘記\n沒有忘記在倉庫裡釘木箱打棧板的汗水記憶\n\n如今\n我將那份聆聽那份細膩的節奏\n帶進App與貼圖裡\n它們是我與使用者之間\n一次次無聲的共振\n\n就像當年那盞燈\n輕輕落在父親的作品上\n\n然後\n有人停下來\n\n安靜地\n看了很久\n\n或許\n那個人就是你",
    stat1_num: "20",
    stat1_txt: "年策展經歷",
    stat2_num: "≈60",
    stat2_txt: "場展覽策劃",
    stat3_num: "4",
    stat3_txt: "大洲足跡",
    apps_title: "原創應用",
    sticker_title: "iMessage 貼圖",
    pf_title: "ProfitFairy 毛利率利潤定價計算機",
    pf_sub: "商業・生產力工具",
    pf_desc:
      "專為電商與實體商家設計的利潤管理系統。一鍵拆分成本、運費、稅金、平台費，即時計算多項參數混搭並支援歷史紀錄查看，讓每個商業決策精準透明。",
    ruby_title: "小主私密日記－月經經期排卵日曆",
    ruby_sub: "生理期追蹤、月經排卵期計算器・女性私密日記",
    ruby_desc:
      "生理期與排卵期精準計算日曆，同時是一本可上鎖的私密日記。融合《黃帝內經》等四大中醫典籍，提供穴位與藥膳食補指南。記錄每一天的心情、瞬間與身體變化。",
    aios_title: "艾奧斯 (AIOS Realm)",
    aios_sub: "解謎・卡牌・故事",
    aios_desc:
      "顛覆傳統2048的立體化腦力解謎。透過十字合成、女神卡牌召喚與記憶碎片重組，逐步解鎖海洋女神的史詩劇情。燒腦策略與抽卡收集並行的益智遊戲。",
    taiger_name: "【台客柴】阿柴的江湖日常：俗擱有力篇",
    taiger_sub: "藍白拖＋復古安全帽＋超派口頭禪，看起來很兇其實超北爛",
    taiger_desc:
      "聊天沒話題？那是因為你少了一隻「台客柴」！本系列收錄江湖吐槽神句與爆笑表情，專門對付已讀不回、需要被狠嗆的朋友。從藍白拖到復古安全帽，超派口頭禪俗擱有力，台到沒朋友。",
    meow1_name: "MeowCAT-1: 辦公室貓爪",
    meow1_sub: "你的每日可愛劑量 / Your Daily Dose of Cuteness",
    meow1_desc: "踏入辦公室日常！冒雨通勤、KPI 奮戰，每個瞬間變得可愛又共鳴。",
    meow2_name: "MeowCAT-2: 職場崩潰日記",
    meow2_sub: "囂張不改，崩潰常來 / Sassy & Stressed-out",
    meow2_desc: "收件箱九頭蛇、老闆緊急要求，辦公貓魂壓力山大，嗆辣態度陪你度過崩潰日常。",
    meow3_name: "MeowCAT-3: 隔間喵趣",
    meow3_sub: "用一聲喵，說一切 / Say It with a Meow",
    meow3_desc: "無限會議、鍵盤旁睏倦小貓，肉球擊掌慶祝成功，毛茸茸夥伴療癒日常。",
    curator_title: "聆聽，然後共振",
    curator_sub: "策展筆記 · 從展場到螢幕",
    curator_p1:
      "策展是一條長河\n\n學會的不是如何展示\n而是如何聆聽\n聆聽作品自身的語言\n聆聽空間的呼吸\n聆聽觀者沉默的凝視\n\n真正的展覽\n是讓這三者找到共振的頻率",
    curator_p2:
      "後來\n這份聆聽被帶進數位世界\n\n每一個App 每一款貼圖\n都不再只是單方面的設計\n像從前聆聽作品那樣\n聆聽每一個使用者的聲音\n他們的想法 困惑 期盼\n一點一滴滲進程式碼裡\n\n這些作品\n是使用者與創作者共同完成的形狀\n\n從來不是那個單獨塑造氛圍的人\n試著站在不同的位置上\n去感受 去揣摩 去共振\n\n小主私密日記是一個例子\n\n一個男性\n要如何設計一個陪伴女性生理期的工具\n沒有答案\n只能去聽 去讀\n去想像那些永遠無法親身經歷的日常\n\n正是這種未知\n讓創作有了溫柔的可能\n\nApp也是這樣\n它們不是被封裝的成品\n而是等待被聆聽 被共鳴 被一起完成的\n\n如同當年曼哈頓\n那盞燈亮起之後\n\n有人安靜地站在父親的作品前\n\n看了很久\n\n策展如此\n創作亦如此\n\n永不落幕",
    expo_role1: "個展策劃 / Solo Exhibitions",
    expo_detail1: "足跡橫跨亞洲、歐洲、美洲、澳洲，為多位藝術家策劃個人展覽",
    expo_role2: "聯展統籌 / Group Shows",
    expo_detail2: "統籌主題性聯展，梳理群體創作中的對話脈絡",
    expo_role3: "藝術博覽會 / Art Fairs",
    expo_fair_note: "諸如 ",
    expo_fair1: "ArtExpo New York / 紐約藝術博覽會 ",
    expo_fair2: "Art Shopping – Carrousel du Louvre / 法國巴黎羅浮宮卡魯塞爾藝術博覽會 ",
    expo_fair3: "Art Taipei / 台北藝術博覽會 ",
    expo_fair4: "AArt Shanghai / 上海城市藝術博覽會 ",
    expo_fair_more: " 等",
    expo_role4: "藝術顧問 / Art Advisor",
    expo_detail4: "私人美術館顧問、藏家與藝術機構策展諮詢",
    expo_note: "足跡遍及四大洲 — 近六十場展覽策劃實踐",
    contact_btn: "聯絡 / 合作",
    contact_note: "策展合作 · 開發委託 · 品牌聯名 · 用戶反饋",
    privacy_link: "隱私權政策",
  },
  "zh-cn": {
    htmlLang: "zh-CN",
    hreflang: "zh-Hans",
    path: "/zh-cn/",
    title: "毕弘伟 Ansel Bi — 策展人 / App 程序员",
    description:
      "策展人 Ansel Bi，近二十年策展经历，策划近六十场展览，足迹遍及亚洲、欧洲、美洲、澳洲。将策展美学注入独立开发的 APP 与贴图。",
    keywords:
      "毕弘伟, Ansel Bi, 策展人, 独立开发者, ProfitFairy, 小主私密日记, 艾奥斯, 台客柴, MeowCAT",
    chinese_name: "毕弘伟",
    name_en: "Ansel Bi",
    nav_works: "作品",
    nav_stickers: "贴图",
    nav_curator: "策展",
    slogan: "将策展的沉默，编译为数字的诗行",
    role: "策展人 / App 程序员",
    hero_desc:
      "某个仓库里\n\n满仓的画\n静止在我面前\n\n不是欣赏\n是打包\n\n打栈板 钉木箱 贴标签 缠胶带\n\n然后\n这些大家伙\n落在比台北慢十二个钟的曼哈顿\n\n那年是雷曼风暴过后\n等待灯光亮起的2009\n\n策展人是儿子\n艺术家是父亲\n\n那是我印象最深的一场策展\n\n我从父亲的作品里学会了聆听\n不是聆听掌声\n而是聆听一件作品从木箱里被取出时\n那道细微的 几乎听不见的呼吸声\n\n还有灯亮之后\n有人走进来\n安静地站在作品前\n那份沉默\n比任何话语都诚实\n\n近二十年过去了\n\n我策划了近六十场展览\n足迹走过亚洲 欧洲 美洲 澳洲\n做过私人美术馆顾问\n为艺术家策划过个展与联展\n也为藏家与机构提供咨询\n\n但我始终没有忘记\n没有忘记在仓库里钉木箱打栈板的汗水记忆\n\n如今\n我将那份聆听那份细腻的节奏\n带进App与贴图里\n它们是我与使用者之间\n一次次无声的共振\n\n就像当年那盏灯\n轻轻落在父亲的作品上\n\n然后\n有人停下来\n\n安静地\n看了很久\n\n或许\n那个人就是你",
    stat1_num: "20",
    stat1_txt: "年策展经历",
    stat2_num: "≈60",
    stat2_txt: "场展览策划",
    stat3_num: "4",
    stat3_txt: "大洲足迹",
    apps_title: "原创应用",
    sticker_title: "iMessage 贴图",
    pf_title: "ProfitFairy 毛利率利润定价计算器",
    pf_sub: "商业・生产力工具",
    pf_desc:
      "专为电商与实体商家设计的利润管理系统。一键拆分成本、运费、税金、平台费，即时计算多项参数混搭并支持历史纪录查看，让每个商业决策精准透明。",
    ruby_title: "小主私密日记－月经经期排卵日历",
    ruby_sub: "生理期追踪、月经排卵期计算器・女性私密日记",
    ruby_desc:
      "生理期与排卵期精准计算日历，同时是一本可上锁的私密日记。融合《黄帝内经》等四大中医典籍，提供穴位与药膳食补指南。记录每一天的心情、瞬间与身体变化。",
    aios_title: "艾奥斯 (AIOS Realm)",
    aios_sub: "解谜・卡牌・故事",
    aios_desc:
      "颠覆传统2048的立体化脑力解谜。透过十字合成、女神卡牌召唤与记忆碎片重组，逐步解锁海洋女神的史诗剧情。烧脑策略与抽卡收集并行的益智游戏。",
    taiger_name: "【台客柴】阿柴的江湖日常：俗搁有力篇",
    taiger_sub: "蓝白拖＋复古安全帽＋超派口头禅，看起来很凶其实超北烂",
    taiger_desc:
      "聊天没话题？那是因为你少了一只「台客柴」！本系列收录江湖吐槽神句与爆笑表情，专门对付已读不回、需要被狠呛的朋友。从蓝白拖到复古安全帽，超派口头禅俗搁有力，台到没朋友。",
    meow1_name: "MeowCAT-1: 办公室猫爪",
    meow1_sub: "你的每日可爱剂量 / Your Daily Dose of Cuteness",
    meow1_desc: "踏入办公室日常！冒雨通勤、KPI 奋战，每个瞬间变得可爱又共鸣。",
    meow2_name: "MeowCAT-2: 职场崩溃日记",
    meow2_sub: "嚣张不改，崩溃常来 / Sassy & Stressed-out",
    meow2_desc: "收件箱九头蛇、老板紧急要求，办公猫魂压力山大，呛辣态度陪你度过崩溃日常。",
    meow3_name: "MeowCAT-3: 隔间喵趣",
    meow3_sub: "用一声喵，说一切 / Say It with a Meow",
    meow3_desc: "无限会议、键盘旁困倦小猫，肉球击掌庆祝成功，毛茸茸伙伴疗愈日常。",
    curator_title: "聆听，然后共振",
    curator_sub: "策展笔记 · 从展场到屏幕",
    curator_p1:
      "策展是一条长河\n\n学会的不是如何展示\n而是如何聆听\n聆听作品自身的语言\n聆听空间的呼吸\n聆听观者沉默的凝视\n\n真正的展览\n是让这三者找到共振的频率",
    curator_p2:
      "后来\n这份聆听被带进数字世界\n\n每一个App 每一款贴图\n都不再只是单方面的设计\n像从前聆听作品那样\n聆听每一个使用者的声音\n他们的想法 困惑 期盼\n一点一滴渗进代码里\n\n这些作品\n是使用者与创作者共同完成的形状\n\n从来不是那个单独塑造氛围的人\n试着站在不同的位置上\n去感受 去揣摩 去共振\n\n小主私密日记是一个例子\n\n一个男性\n要如何设计一个陪伴女性生理期的工具\n没有答案\n只能去听 去读\n去想象那些永远无法亲身经历的日常\n\n正是这种未知\n让创作有了温柔的可能\n\nApp也是这样\n它们不是被封装的成品\n而是等待被聆听 被共鸣 被一起完成的\n\n如同当年曼哈顿\n那盏灯亮起之后\n\n有人安静地站在父亲的作品前\n\n看了很久\n\n策展如此\n创作亦如此\n\n永不落幕",
    expo_role1: "个展策划 / Solo Exhibitions",
    expo_detail1: "足迹横跨亚洲、欧洲、美洲、澳洲，为多位艺术家策划个人展览",
    expo_role2: "联展统筹 / Group Shows",
    expo_detail2: "统筹主题性联展，梳理群体创作中的对话脉络",
    expo_role3: "艺术博览会 / Art Fairs",
    expo_fair_note: "诸如 ",
    expo_fair1: "ArtExpo New York / 纽约艺术博览会 ",
    expo_fair2: "Art Shopping – Carrousel du Louvre / 法国巴黎罗浮宫卡鲁塞尔艺术博览会 ",
    expo_fair3: "Art Taipei / 台北艺术博览会 ",
    expo_fair4: "AArt Shanghai / 上海城市艺术博览会 ",
    expo_fair_more: " 等",
    expo_role4: "艺术顾问 / Art Advisor",
    expo_detail4: "私人美术馆顾问、藏家与艺术机构策展咨询",
    expo_note: "足迹遍及四大洲 — 近六十场展览策划实践",
    contact_btn: "联络 / 合作",
    contact_note: "策展合作 · 开发委托 · 品牌联名 · 用户反馈",
    privacy_link: "隐私权政策",
  },
  en: {
    htmlLang: "en",
    hreflang: "en",
    path: "/en/",
    title: "Ansel Bi — Curator / App Developer",
    description:
      "Curator and indie app developer Ansel Bi. Nearly 20 years curating ~60 exhibitions across four continents. Bringing curatorial aesthetics to original apps and iMessage stickers.",
    keywords:
      "Ansel Bi, curator, indie developer, ProfitFairy, RubyDays, AIOS Realm, Taiger Shiba, MeowCAT",
    chinese_name: "",
    name_en: "Ansel Bi",
    nav_works: "Works",
    nav_stickers: "Stickers",
    nav_curator: "Curating",
    slogan: "Compiling curatorial silence into digital poetry",
    role: "Curator / App Developer",
    hero_desc:
      "Inside a certain warehouse\n\nPaintings filled the room\nStill before me\n\nNot to admire them\nTo pack them\n\nPalletizing nailing crates labeling wrapping tape\n\nThen\nThese heavy giants\nLanded in Manhattan twelve hours behind Taipei\n\nThe year after the Lehman storm\nWaiting for the lights to rise in 2009\n\nThe curator was a son\nThe artist was his father\n\nIt was the curatorial work I remember most vividly\n\nFrom my father's work I learned to listen\nNot to applause\nBut to the faint almost inaudible breath\nOf a piece being lifted from its crate\n\nAnd after the lights came up\nSomeone would walk in\nAnd stand quietly in front of the work\nThat silence\nWas more honest than any words\n\nNearly twenty years have passed\n\nI have curated nearly sixty exhibitions\nTraveling across Asia Europe the Americas and Australia\nServed as a private museum advisor\nCurated solo and group shows for artists\nAnd offered consultation to collectors and institutions\n\nBut I have never forgotten\nNever forgotten the sweaty memory of nailing crates and palletizing in the warehouse\n\nNow\nI bring that same listening that same delicate rhythm\nInto apps and stickers\nThey are the silent resonance\nBetween me and every user\n\nLike that light\nSoftly falling on my father's work\n\nThen\nSomeone stopped\n\nQuietly\nLooked for a long long time\n\nPerhaps\nThat someone is you",
    stat1_num: "20",
    stat1_txt: "Years",
    stat2_num: "≈60",
    stat2_txt: "Exhibitions",
    stat3_num: "4",
    stat3_txt: "Continents",
    apps_title: "Original Apps",
    sticker_title: "iMessage Stickers",
    pf_title: "ProfitFairy Gross Margin Calc",
    pf_sub: "Business · Productivity",
    pf_desc:
      "Profit management for e-commerce & retail. Split costs, shipping, taxes, platform fees instantly, calculate multiple mixed parameters in real time with history log support. Precision for every decision.",
    ruby_title: "RubyDays: TCM Herbal Wellness Calendar",
    ruby_sub: "Period Tracker, Ovulation Calculator & Private Diary",
    ruby_desc:
      "Accurate period & ovulation calendar, plus a lockable private diary. Integrates 4 TCM classics, acupressure, and medicinal recipes. Record daily moods, moments, and physical changes.",
    aios_title: "AIOS Realm: Divinity Reborn",
    aios_sub: "Puzzle · Cards · Story",
    aios_desc:
      "A 2048-evolution puzzle game. Merge goddess cards, unlock epic oceanic narrative. A puzzle game where strategic brain-teasing and card collection go hand in hand.",
    taiger_name: "Taiger Shiba: Jianghu Daily",
    taiger_sub: "Blue slippers + retro helmet + gangster phrases. Looks fierce but hilariously silly",
    taiger_desc:
      "No chat topics? You're missing Taiger Shiba! Gangster one-liners and hilarious expressions for ghosting friends and spicy group chats. Blue slippers, retro helmet, Taiwan swagger—collect them all.",
    meow1_name: "MeowCAT-1: Office Paws",
    meow1_sub: "Your Daily Dose of Cuteness",
    meow1_desc: "Office life reimagined! Rainy commutes, KPI battles—every moment cuter and more relatable.",
    meow2_name: "MeowCAT-2: Corporate Meltdown",
    meow2_sub: "Sassy & Stressed-out",
    meow2_desc: "Inbox hydra, boss emergencies—sassy office cat attitude for your meltdown days.",
    meow3_name: "MeowCAT-3: Cubicle Tails",
    meow3_sub: "Say It with a Meow",
    meow3_desc: "Endless meetings, sleepy keyboard cat, paw-high-fives for wins—a fluffy cubicle companion.",
    curator_title: "Listen, Then Resonate",
    curator_sub: "Curatorial Notes · From Galleries to Screens",
    curator_p1:
      "Curating is a long river\n\nWhat I learned was not how to display\nBut how to listen\nTo listen to the language of the work\nThe breath of the space\nThe silent gaze of the viewer\n\nA true exhibition\nIs where these three find a frequency of resonance",
    curator_p2:
      "Later\nThat listening found its way into the digital world\n\nEvery app every sticker\nIs no longer just a one-sided design\nJust as I once listened to artworks\nI now listen to every user's voice\nTheir thoughts their confusions their hopes\nSeeping into the code drop by drop\n\nThese works\nAre shapes co-created by users and the creator\n\nI am never the one who shapes the atmosphere alone\nI try to stand in different positions\nTo feel to empathize to resonate\n\nRubyDays is one example\n\nHow does a man design a tool\nTo accompany women through their cycles\nI don't have the answer\nI can only listen read\nAnd imagine the daily realities I will never experience firsthand\n\nIt is precisely this unknown\nThat gives creation its gentle possibility\n\nApps are the same\nThey are not sealed finished products\nThey are things waiting to be heard to be resonated with to be completed together\n\nJust like that night in Manhattan\nAfter the lights came up\n\nSomeone stood quietly in front of my father's work\n\nAnd looked for a long time\n\nCurating is like this\nCreation is like this\n\nIt never ends",
    expo_role1: "Solo Exhibitions",
    expo_detail1: "Spanning Asia Europe Americas Australia curated solo shows for multiple artists",
    expo_role2: "Group Shows",
    expo_detail2: "Organized thematic group exhibitions articulating dialogues within collective creations",
    expo_role3: "Art Fairs",
    expo_fair_note: "Including ",
    expo_fair1: "ArtExpo New York ",
    expo_fair2: "Art Shopping – Carrousel du Louvre ",
    expo_fair3: "Art Taipei ",
    expo_fair4: "AArt Shanghai ",
    expo_fair_more: " among others",
    expo_role4: "Art Advisor",
    expo_detail4: "Consulting for private museums collectors and art institutions",
    expo_note: "Spanning four continents nearly sixty curated exhibitions",
    contact_btn: "Contact / Collaborate",
    contact_note: "Curatorial · Development · Brand Collaboration · Feedback",
    privacy_link: "Privacy Policy",
  },
  ja: {
    htmlLang: "ja",
    hreflang: "ja",
    path: "/ja/",
    title: "Ansel Bi — キュレーター / アプリ開発者",
    description:
      "キュレーター兼インディーアプリ開発者 Ansel Bi。約20年間、四大陸で約60の展覧会を企画。キュレーションの美学をオリジナルアプリとiMessageステッカーに注ぐ。",
    keywords:
      "Ansel Bi, キュレーター, インディー開発者, ProfitFairy, RubyDays, AIOS Realm, 台客柴, MeowCAT",
    chinese_name: "",
    name_en: "Ansel Bi",
    nav_works: "作品",
    nav_stickers: "ステッカー",
    nav_curator: "キュレーション",
    slogan: "キュレーションの沈黙を、デジタルの詩行へと編む",
    role: "キュレーター / アプリ開発者",
    hero_desc:
      "ある倉庫の中で\n\n倉庫いっぱいの画が\n目の前で静まり返っていた\n\n鑑賞するためではない\n梱包するためだ\n\nパレットに載せ 木箱を釘付け ラベルを貼り テープを巻く\n\nそして\nこの大きな塊たちが\n台北より十二時間遅いマンハッタンに降り立った\n\nそれはリーマンショックのあと\n灯がともるのを待っていた2009年\n\nキュレーターは息子\nアーティストは父\n\n記憶に最も深く残るキュレーションだった\n\n父の作品から私は「聴く」ことを学んだ\n拍手を聴くのではない\n木箱から作品が取り出されるとき\nかすかで ほとんど聞こえない息づかいを聴くのだ\n\nそして灯がともると\n誰かが入ってきて\n作品の前に静かに立つ\nその沈黙は\nどんな言葉よりも誠実だった\n\n二十年近くが過ぎた\n\n私は約六十の展覧会を企画し\nアジア ヨーロッパ 南北アメリカ オーストラリアを歩いてきた\n私立美術館のアドバイザーを務め\nアーティストの個展やグループ展を企画し\nコレクターや機関へのコンサルティングも行ってきた\n\nしかし私は決して忘れていない\n倉庫で木箱を釘付け パレットを組んだ汗の記憶を忘れていない\n\n今\nその聴き方 その繊細なリズムを\nアプリとステッカーに持ち込んでいる\nそれらは私とユーザーとの間の\n何度も重なる無声の共鳴だ\n\nあの頃の灯のように\n父の作品にそっと降り注ぐように\n\nそして\n誰かが立ち止まり\n\n静かに\n長いあいだ見つめた\n\nもしかしたら\nその人はあなたかもしれない",
    stat1_num: "20",
    stat1_txt: "年のキュレーション",
    stat2_num: "≈60",
    stat2_txt: "展覧会企画",
    stat3_num: "4",
    stat3_txt: "大陸の足跡",
    apps_title: "オリジナルアプリ",
    sticker_title: "iMessage ステッカー",
    pf_title: "ProfitFairy 粗利率・利益 価格計算",
    pf_sub: "原価・販売価格を即計算 手数料・税も",
    pf_desc:
      "EC・小売向けの利益管理ツール。コスト、送料、税金、プラットフォーム手数料を一括分解し、複数パラメータの組み合わせをリアルタイム計算。履歴ログ対応で、すべての意思決定を透明に。",
    ruby_title: "小主日記：老中醫漢方養生調理日曆，生理期追蹤、月經排卵期計算",
    ruby_sub: "",
    ruby_desc:
      "生理周期と排卵日を正確に計算するカレンダーと、ロック可能なプライベート日記。四大中医古典を融合し、ツボ押しや薬膳レシピを提供。毎日の気分、瞬間、体の変化を記録。",
    aios_title: "アイオス（AIOS Realm）",
    aios_sub: "2048を超えた、挑戦する勇気ある？",
    aios_desc:
      "2048を進化させた立体パズルゲーム。女神カードを合成し、海洋女神の壮大な物語を解き放つ。戦略的な頭脳パズルとカード収集が融合したゲーム。",
    taiger_name: "【台客柴】阿柴的江湖日常：俗擱有力篇",
    taiger_sub: "藍白拖＋復古安全帽＋超派口頭禪，看起來很兇其實超北爛",
    taiger_desc:
      "話題に困った？台客柴がいないだけかも！台湾スラングの名セリフと爆笑スタンプで、既読スルーや辛口チャットに最適。ビーチサンダルからレトロヘルメットまで、台湾のノリ満載。",
    meow1_name: "MeowCAT-1: オフィスネコ",
    meow1_sub: "あなたの毎日の可愛さの摂取量",
    meow1_desc: "オフィスライフを再解釈！雨の通勤、KPIとの戦い—すべての瞬間がもっとかわいく、共感できるように。",
    meow2_name: "MeowCAT-2: 社畜のメンタル爆破",
    meow2_sub: "ツンデレ&脳筋破裂",
    meow2_desc: "受信箱の九頭龍、上司の緊急依頼—生意気なオフィス猫が、崩壊寸前の日常を支える。",
    meow3_name: "MeowCAT-3: 業務にゃん",
    meow3_sub: "鳴き声で、伝えよう",
    meow3_desc: "終わらない会議、キーボード横の眠そうな猫、成功を祝う肉球ハイタッチ—ふわふわの相棒が日常を癒す。",
    curator_title: "聴き、そして共鳴する",
    curator_sub: "キュレーションノート · ギャラリーからスクリーンへ",
    curator_p1:
      "キュレーションは長い川のようなもの\n\n学んだのは展示の仕方ではない\n聴くことだ\n作品自身の言葉を聴く\n空間の呼吸を聴く\n観客の沈黙のまなざしを聴く\n\n本当の展覧会とは\nこの三者が共鳴の周波数を見つける場所だ",
    curator_p2:
      "やがて\nその聴き方はデジタルの世界へと入っていった\n\nすべてのアプリ すべてのステッカーは\nもはや一方的なデザインではない\nかつて作品を聴いたように\n今はすべてのユーザーの声を聴く\n彼らの想い 迷い 期待が\n一滴一滴コードに染み込んでいく\n\nこれらの作品は\nユーザーと創作者がともに形づくるもの\n\n雰囲気を一人で作る者ではない\nさまざまな立場に立ち\n感じ 想像し 共鳴しようとする\n\nRubyDaysはその一例\n\n男性が\n女性の生理周期に寄り添うツールをどう設計するか\n答えはない\n聴き 読み\n決して自分では経験できない日常を想像するしかない\n\nまさにこの未知こそが\n創作にやさしさの可能性を与える\n\nアプリも同じだ\n封じ込められた完成品ではない\n聴かれ 共鳴され ともに完成されるものを待っている\n\nマンハッタンのあの夜\n灯がともったあと\n\n誰かが父の作品の前に静かに立ち\n\n長いあいだ見つめていた\n\nキュレーションも\n創作も\n\n終わることはない",
    expo_role1: "個展企画 / Solo Exhibitions",
    expo_detail1: "アジア・ヨーロッパ・南北アメリカ・オーストラリアで複数のアーティストの個展を企画",
    expo_role2: "グループ展統括 / Group Shows",
    expo_detail2: "テーマ性のあるグループ展を統括し、集合的創作の中の対話を紡ぐ",
    expo_role3: "アートフェア / Art Fairs",
    expo_fair_note: "例：",
    expo_fair1: "ArtExpo New York ",
    expo_fair2: "Art Shopping – Carrousel du Louvre ",
    expo_fair3: "Art Taipei ",
    expo_fair4: "AArt Shanghai ",
    expo_fair_more: " など",
    expo_role4: "アートアドバイザー / Art Advisor",
    expo_detail4: "私立美術館、コレクター、美術機関へのキュレーションコンサルティング",
    expo_note: "四大陸にわたる足跡 — 約六十の展覧会企画",
    contact_btn: "お問い合わせ / コラボレーション",
    contact_note: "キュレーション · 開発委託 · ブランドコラボ · フィードバック",
    privacy_link: "プライバシーポリシー",
  },
  ko: {
    htmlLang: "ko",
    hreflang: "ko",
    path: "/ko/",
    title: "Ansel Bi — 큐레이터 / 앱 개발자",
    description:
      "큐레이터이자 인디 앱 개발자 Ansel Bi. 약 20년간 4대륙에서 약 60회의 전시를 기획했습니다. 큐레이션 미학을 오리지널 앱과 iMessage 스티커에 담습니다.",
    keywords:
      "Ansel Bi, 큐레이터, 인디 개발자, ProfitFairy, RubyDays, AIOS Realm, 타이거 시바, MeowCAT",
    chinese_name: "",
    name_en: "Ansel Bi",
    nav_works: "작품",
    nav_stickers: "스티커",
    nav_curator: "큐레이션",
    slogan: "큐레이션의 침묵을 디지털 시로 엮다",
    role: "큐레이터 / 앱 개발자",
    hero_desc:
      "어느 창고 안에서\n\n창고 가득 그림이\n내 앞에서 고요했다\n\n감상하기 위함이 아니라\n포장하기 위함이었다\n\n팔레트 적재 나무 상자 못 박기 라벨 붙이기 테이프 감기\n\n그리고\n이 거대한 것들이\n타이베이보다 열두 시간 늦은 맨해튼에 내려앉았다\n\n그해는 리먼 쇼크 이후\n조명이 켜지기를 기다리던 2009년\n\n큐레이터는 아들\n예술가는 아버지\n\n가장 깊이 기억에 남는 큐레이션이었다\n\n아버지의 작품에서 나는 듣는 법을 배웠다\n박수를 듣는 것이 아니라\n상자에서 작품이 꺼내질 때\n거의 들리지 않는 미세한 숨결을 듣는 것이다\n\n그리고 불이 켜진 뒤\n누군가 들어와\n작품 앞에 조용히 서 있었다\n그 침묵은\n어떤 말보다도 진실했다\n\n거의 이십 년이 지났다\n\n나는 약 육십 회의 전시를 기획했고\n아시아 유럽 아메리카 오스트레일리아를 걸었다\n사립 미술관 자문을 맡았고\n예술가의 개인전과 단체전을 기획했으며\n수집가와 기관에 컨설팅을 제공했다\n\n하지만 나는 결코 잊지 않았다\n창고에서 나무 상자에 못을 박고 팔레트를 쌓던 땀의 기억을 잊지 않았다\n\n이제\n그 듣는 방식 그 섬세한 리듬을\n앱과 스티커에 담고 있다\n그것들은 나와 사용자 사이의\n끊임없는 무음의 공명이다\n\n그때 그 불빛처럼\n아버지의 작품 위에 부드럽게 내려앉듯\n\n그리고\n누군가 멈춰 섰다\n\n조용히\n오랫동안 바라보았다\n\n어쩌면\n그 사람이 바로 당신일지도 모른다",
    stat1_num: "20",
    stat1_txt: "년 큐레이션",
    stat2_num: "≈60",
    stat2_txt: "전시 기획",
    stat3_num: "4",
    stat3_txt: "대륙 발자취",
    apps_title: "오리지널 앱",
    sticker_title: "iMessage 스티커",
    pf_title: "ProfitFairy 마진·수익·가격 계산기",
    pf_sub: "원가 판매가 즉시 계산｜수수료·세금",
    pf_desc:
      "이커머스·소매를 위한 이익 관리 도구. 비용, 배송비, 세금, 플랫폼 수수료를 즉시 분해하고 여러 파라미터를 실시간으로 계산합니다. 기록 로그 지원으로 모든 결정을 투명하게.",
    ruby_title: "小主日記：老中醫漢方養生調理日曆，生理期追蹤、月經排卵期計算",
    ruby_sub: "",
    ruby_desc:
      "정확한 생리·배란 캘린더와 잠금 가능한 프라이빗 다이어리. 4대 한의학 고전을 통합하고 지압·약식 레시피를 제공합니다. 매일의 기분, 순간, 신체 변화를 기록하세요.",
    aios_title: "아이오스（AIOS Realm）",
    aios_sub: "2048을 넘어, 도전할 용기 있나?",
    aios_desc:
      "2048을 진화시킨 입체 퍼즐 게임. 여신 카드를 합성하고 바다 여신의 서사를 해제하세요. 전략적 두뇌 퍼즐과 카드 수집이 함께하는 게임.",
    taiger_name: "【台客柴】阿柴的江湖日常：俗擱有力篇",
    taiger_sub: "藍白拖＋復古安全帽＋超派口頭禪，看起來很兇其實超北爛",
    taiger_desc:
      "대화 주제가 없나요? 타이거 시바가 없어서 그렇습니다! 대만식 명대사와 웃긴 이모티콘으로 읽씹 친구와 매운맛 채팅에 딱 맞습니다. 슬리퍼부터 레트로 헬멧까지, 대만 감성 가득.",
    meow1_name: "MeowCAT-1: 사무실 고양이",
    meow1_sub: "당신의 매일 매력 복용량",
    meow1_desc: "오피스 라이프를 새롭게! 비 오는 출근, KPI 전투—모든 순간이 더 귀엽고 공감되게.",
    meow2_name: "MeowCAT-2: 회사 괴롭힘 실태",
    meow2_sub: "삐졌음 스트레스 폭발함",
    meow2_desc: "받은편지함 히드라, 보스의 긴급 요청—당당한 오피스 고양이가 무너지는 일상을 함께합니다.",
    meow3_name: "MeowCAT-3: 사무실 야옹이",
    meow3_sub: "야옹으로 전해요",
    meow3_desc: "끝없는 회의, 키보드 옆 졸린 고양이, 성공을 축하하는 발바닥 하이파이브—푹신한 동료가 일상을 치유합니다.",
    curator_title: "듣고, 그다음 공명하다",
    curator_sub: "큐레이션 노트 · 갤러리에서 스크린으로",
    curator_p1:
      "큐레이션은 긴 강과 같다\n\n배운 것은 어떻게 보여줄 것인가가 아니라\n어떻게 들을 것인가다\n작품 자체의 언어를 듣고\n공간의 숨결을 듣고\n관객의 침묵하는 시선을 듣는다\n\n진정한 전시란\n이 셋이 공명의 주파수를 찾는 곳이다",
    curator_p2:
      "나중에\n그 듣는 방식은 디지털 세계로 들어갔다\n\n모든 앱 모든 스티커는\n더 이상 일방적인 디자인이 아니다\n예전에 작품을 듣듯\n이제는 모든 사용자의 목소리를 듣는다\n그들의 생각 혼란 기대가\n한 방울씩 코드에 스며든다\n\n이 작품들은\n사용자와 창작자가 함께 완성하는 형태다\n\n분위기를 혼자 만드는 사람이 아니다\n다른 위치에 서서\n느끼고 공감하고 공명하려 한다\n\nRubyDays가 한 예이다\n\n남성이\n여성의 생리 주기를 함께하는 도구를 어떻게 설계할 것인가\n답은 없다\n듣고 읽고\n결코 직접 경험할 수 없는 일상을 상상할 뿐이다\n\n바로 이 미지가\n창작에 부드러운 가능성을 준다\n\n앱도 마찬가지다\n봉인된 완성품이 아니라\n들려지고 공명되고 함께 완성되기를 기다리는 것들이다\n\n맨해튼의 그날 밤\n불이 켜진 뒤\n\n누군가 아버지의 작품 앞에 조용히 서서\n\n오랫동안 바라보았다\n\n큐레이션도\n창작도\n\n끝나지 않는다",
    expo_role1: "개인전 기획 / Solo Exhibitions",
    expo_detail1: "아시아·유럽·아메리카·오스트레일리아를 아우르며 여러 예술가의 개인전 기획",
    expo_role2: "단체전 기획 / Group Shows",
    expo_detail2: "주제성 단체전을 기획하고 집단 창작 속 대화의 맥락을 정리",
    expo_role3: "아트페어 / Art Fairs",
    expo_fair_note: "예: ",
    expo_fair1: "ArtExpo New York ",
    expo_fair2: "Art Shopping – Carrousel du Louvre ",
    expo_fair3: "Art Taipei ",
    expo_fair4: "AArt Shanghai ",
    expo_fair_more: " 등",
    expo_role4: "아트 어드바이저 / Art Advisor",
    expo_detail4: "사립 미술관, 수집가, 미술 기관 큐레이션 컨설팅",
    expo_note: "4대륙에 걸친 발자취 — 약 60회의 전시 기획",
    contact_btn: "문의 / 협업",
    contact_note: "큐레이션 · 개발 의뢰 · 브랜드 콜라보 · 피드백",
    privacy_link: "개인정보 처리방침",
  },
};
